title: "Main of Iron"
description: "Blog o przygotowaniach do IRONMAN 70.3 Pozna≈Ñ 2026"
theme: minima
author: "Bartosz Milewski"
baseurl: "/man-of-iron"
url: "https://bmil.github.io"
minima:
  show_excerpts: true
  nav_pages:
    - index.md
